set nocompatible
filetype off "required by vundle

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'gmarik/Vundle.vim'

Plugin 'scrooloose/nerdtree.git'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'tomtom/tcomment_vim'
Plugin 'majutsushi/tagbar'
Plugin 'evidens/vim-twig'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/unite.vim'
Plugin 'mileszs/ack.vim'
Plugin 'amiorin/vim-project'
Plugin 'kien/ctrlp.vim'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'airblade/vim-gitgutter'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tacahiroy/ctrlp-funky'
Plugin 'scrooloose/syntastic'
Plugin 'Valloric/YouCompleteMe'
Plugin 'spf13/vim-autoclose'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'pangloss/vim-javascript'
call vundle#end()

filetype plugin indent on

"vim-autoclose
let g:autoclose_vim_commentmode = 1

"main
set encoding=utf-8
set undolevels=1000

set showmatch
set showmode
set showcmd

let g:mapleader = "\<Space>"
inoremap jk <Esc>
inoremap kj <Esc>
nmap <leader>ev :edit $MYVIMRC<CR>
nmap <leader>ws :w !sudo tee %<CR>
nmap <leader>w :w<CR>

set number
set ttyfast

map j gj
map k gk

set splitbelow
set splitright

nmap <leader>h :noh<CR>

"command line mode
set wildmenu
set wildmode=longest:list,full
set wildignorecase
set wildignore+=*/.git/*,*/tmp/*,*/cache/*

"colors
syntax enable
colorscheme molokai
let g:rehash256 = 1
set background=dark
set t_Co=256

"indent
set autoindent
set copyindent
set smartindent
set smarttab
set expandtab
set shiftwidth=4
set tabstop=4

"gVim options
set guioptions-=T
set guioptions-=r
set guioptions-=L
set guioptions-=m
set guifont=Liberation\ Mono\ for\ Powerline\ 12
set mousehide
set linespace=1

"searching
set ignorecase
set smartcase
set incsearch
set magic

"Don't redraw while executing macros(performace)
set lazyredraw

"no anoying sound on errors
set noerrorbells
set novisualbell

"turn off backup
set nobackup
set noswapfile
set nowb

set lbr
set tw=500
set nowrap

" vim-airline
let g:airline_theme='molokai'
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
set laststatus=2

"nerdtree
nnoremap <leader>n :NERDTreeTabsToggle<CR>
nnoremap <leader>r :NERDTreeFind<CR>
let g:NERDTreeShowHidden=1
let g:NERDTreeChDirMode = 2
let g:nerdtree_tabs_open_on_gui_startup = 0
let g:NERDTreeWinSize = 50

"smart way to move between windows
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l
nnoremap <leader>v <C-w>v<C-w>l
nnoremap <leader>s <C-w>s

" Resize splitted views faster
" nnoremap <C-h> 3<C-w><
" nnoremap <C-l> 3<C-w>>
" nnoremap <C-k> 3<C-w>+
" nnoremap <C-j> 3<C-w>-

"speed up scrolling
set scrolljump=10

" Instead of 1 line, move 3 at a time
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>


" wrapping lines in visual mode
vnoremap < <gv
vnoremap > >gv

" DBGPavim
let g:dbgPavimPort = 9000
let g:dbgPavimBreakAtEntry = 0

" tagbar
nnoremap <leader>l :TagbarToggle<CR>
nnoremap <leader>t :TagbarOpenAutoClose<CR>
let g:tagbar_width = 45

" use system clipboard instead of default vim
set clipboard=unnamedplus

" easymotion
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
let g:EasyMotion_startofline = 0 " keep cursor colum when JK motion

" YCM
set completeopt=menuone,longest

"ultiSnips
let g:UltiSnipsSnippetDirectories = ["UltiSnips", "ultisnips-snippets"]
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
let g:UltiSnipsExpandTrigger="<S-CR>"

"fugitive
nnoremap <silent> <leader>gs :Gstatus<CR>
nnoremap <silent> <leader>gd :Gdiff<CR>

"project
let g:project_use_nerdtree = 1
set rtp+=~/.vim/bundle/vim-project/
call project#rc("~/projects")

"unite
nnoremap <Leader>u :<C-u>Unite -no-split -buffer-name=files -start-insert file_rec/git<CR>
nnoremap <Leader>f :<C-u>Unite -no-split -buffer-name=files -start-insert file<CR>
nnoremap <Leader>g :<C-u>Unite -no-split grep:.<CR>
if executable('ag')
    let g:unite_source_grep_command='ag'
    let g:unite_source_grep_default_opts='--nocolor --nogroup -S -C4'
    let g:unite_source_grep_recursive_opt=''
endif

"ctrlP
let g:ctrlp_working_path_mode = 'rw'
let g:ctrlp_extensions = ['funky']
nnoremap <Leader>b :CtrlPBuffer<CR>

if executable('ag')
    let s:ctrlp_fallback = 'ag %s --nocolor -l -g ""'
elseif executable('ack-grep')
    let s:ctrlp_fallback = 'ack-grep %s --nocolor -f'
elseif executable('ack')
    let s:ctrlp_fallback = 'ack %s --nocolor -f'
else
    let s:ctrlp_fallback = 'find %s -type f'
endif

"gitgutter
let g:gitgutter_enabled = 0

"syntastic
let g:syntastic_php_checkers = ['php']
let g:airline#extensions#syntastic#enabled = 1
let g:syntastic_check_on_open=1

"local config
if filereadable(expand('~/dotfiles/vim/vimrc.local'))
    source ~/dotfiles/vim/vimrc.local
endif

"markdown syntax fix
au BufRead,BufNewFile *.md set filetype=markdown
